### ISSUE TITLE
Write a gulp task to convert the markdown file in this repository to html

### ISSUE THREAD

**Issue by faza** [doselect/lucy#1]

**Comment by Saikat-Sinha** [comment]
To start the Task:
1. `npm install`  (1st time only)
2. `grunt`

**Comment by dolftax** [comment]
We use gulp to run these kind of tasks. @Saikat-Sinha Use this package - https://www.npmjs.com/package/gulp-markdown

**Comment by Saikat-Sinha** [comment]
@dolftax  Replaced Grunt by Gulp [here](https://github.com/doselect/lucy/pull/2)

**Comment by Saikat-Sinha** [comment]
To start Task :
1. `npm install` 
2. `gulp`
